package types

//Value ...
type Value string

const (
	//Array ...
	Array Value = "Array"
	//JSON ...
	JSON Value = "JSON"
	//BigInt ...
	BigInt Value = "BigInt"
	//Boolean ...
	Boolean Value = "Boolean"
	//Datetime ...
	Datetime Value = "Datetime"
	//Date ...
	Date Value = "Date"
	//Time ...
	Time Value = "Time"
	//Year ...
	Year Value = "Year"
	//Timestamp ...
	Timestamp Value = "Timestamp"
	//Decimal ...
	Decimal Value = "Decimal"
	//Integer ...
	Integer Value = "Integer"
	//SmallInt ...
	SmallInt Value = "SmallInt"
	//String ...
	String Value = "String"
	//Text ...
	Text Value = "Text"
	//Binary ...
	Binary Value = "Binary"
	//Blob ...
	Blob Value = "Blob"
	//Float ...
	Float Value = "Float"
	//Unknown ...
	Unknown Value = "Unknown"
)
