package types

//Value ...
type Value string

const (
	//Array ...
	Array Value = "Array"
	//SimpleArray ...
	SimpleArray Value = "SimpleArray"
	//JSONArray ...
	JSONArray Value = "JSONArray"
	//JSON ...
	JSON Value = "JSON"
	//BigInt ...
	BigInt Value = "BigInt"
	//Boolean ...
	Boolean Value = "Boolean"
	//Datetime ...
	Datetime Value = "Datetime"
	//DatetimeInmutable ...
	DatetimeInmutable Value = "DatetimeInmutable"
	//DatetimeTZ ...
	DatetimeTZ Value = "DatetimeTZ"
	//Date ...
	Date Value = "Date"
	//DateInmutable ...
	DateInmutable Value = "DateInmutable"
	//Time ...
	Time Value = "Time"
	//Timestamp ...
	Timestamp Value = "Timestamp"
	//TimeInmutable ...
	TimeInmutable Value = "TimeInmutable"
	//Decimal ...
	Decimal Value = "Decimal Value = "
	//Integer ...
	Integer Value = "Integer"
	//Object ...
	Object Value = "Object"
	//SmallInt ...
	SmallInt Value = "SmallInt"
	//String ...
	String Value = "String"
	//Text ...
	Text Value = "Text"
	//Binary ...
	Binary Value = "Binary"
	//Blob ...
	Blob Value = "Blob"
	//Float ...
	Float Value = "Float"
	//GUID ...
	GUID Value = "GUID"
	//DateInterval ...
	DateInterval Value = "DateInterval"
	//Unknown ...
	Unknown Value = "Unknown"
)
