package types

const (
	//SpecialEmail ...
	SpecialEmail Value = "SpecialEmail"
	//SpecialPassword ...
	SpecialPassword Value = "SpecialPassword"
	//SpecialURL ...
	SpecialURL Value = "SpecialURL"
	//SpecialHTML ...
	SpecialHTML Value = "SpecialHTML"
)
